<template>
  <main class="flex-1 min-w-0">
    <div class="max-w-4xl mx-auto px-6 py-10 lg:px-8 lg:py-12">
      <slot />
      <footer class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-700 text-center text-sm text-gray-500 dark:text-gray-400">
        Generated by <a href="https://github.com/metanorma/metanorma-docbook" class="text-blue-600 dark:text-blue-400 hover:underline">Metanorma Docbook</a> gem
      </footer>
    </div>
  </main>
</template>

<script setup lang="ts">
</script>
