<template>
  <main class="flex-1 min-w-0">
    <div class="max-w-4xl mx-auto px-6 py-10 lg:px-8 lg:py-12">
      <slot />
      <footer class="content-footer mt-16 pt-8 border-t text-center text-sm">
        Generated by <a href="https://github.com/metanorma/metanorma-docbook" class="content-link hover:underline">Metanorma Docbook</a> gem
      </footer>
    </div>
  </main>
</template>

<script setup lang="ts">
</script>

<style scoped>
.content-footer {
  border-color: var(--ebook-border);
  color: var(--ebook-text-muted);
}
.content-link {
  color: var(--ebook-link-color);
}
</style>
