<template>
  <EbookContainer :class="['h-screen overflow-hidden', ebookStore.getThemeClass()]" :style="ebookStore.getCssVariables()">
    <!-- Mobile overlay -->
    <div
      v-if="uiStore.sidebarOpen"
      @click="uiStore.closeSidebar"
      class="fixed inset-0 bg-black/50 z-40 lg:hidden"
    ></div>

    <AppSidebar />

    <!-- Ebook Top Bar -->
    <EbookTopBar
      :title="documentStore.title"
      :sidebar-open="uiStore.sidebarOpen"
      @toggle-toc="toggleToc"
      @toggle-settings="ebookStore.toggleSettings"
    />

    <main ref="mainContent" :class="[
      'h-screen overflow-y-auto pt-14 transition-all duration-200',
      uiStore.sidebarOpen ? 'lg:pl-[280px]' : ''
    ]" @scroll="handleScroll">
      <!-- Active section breadcrumb -->
      <BreadcrumbBar v-if="ancestorChain.length > 0" :ancestor-chain="ancestorChain" />

      <div class="px-6 py-10 lg:px-8 lg:py-12 mx-auto" :style="{ maxWidth: '72rem', margin: '0 auto' }">
        <!-- DocbookMirror format (ProseMirror-style) -->
        <div v-if="documentStore.mirrorDocument" class="db-content">
          <MirrorRenderer :blocks="documentStore.mirrorDocument.content || []" />
        </div>

        <!-- Footer -->
        <footer class="app-footer mt-16 pt-8 border-t text-center text-sm">
          Generated by <a href="https://github.com/metanorma/metanorma-docbook" class="app-footer-link hover:underline">Metanorma Docbook</a> gem
        </footer>
      </div>
    </main>

    <SearchModal />
    <SettingsPanel />

    <!-- Keyboard shortcut listener -->
    <Teleport to="body">
      <div @keydown="handleGlobalKeydown"></div>
    </Teleport>
  </EbookContainer>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, computed, ref } from 'vue'
import { useDocumentStore, type TocItem } from '@/stores/documentStore'
import { useUiStore } from '@/stores/uiStore'
import { useEbookStore } from '@/composables/useEbookStore'
import AppSidebar from '@/components/AppSidebar.vue'
import SearchModal from '@/components/SearchModal.vue'
import SettingsPanel from '@/components/SettingsPanel.vue'
import MirrorRenderer from '@/components/MirrorRenderer.vue'
import EbookTopBar from '@/components/EbookTopBar.vue'
import EbookContainer from '@/components/EbookContainer.vue'
import BreadcrumbBar from '@/components/BreadcrumbBar.vue'
import { findAncestorChain } from '@/utils/breadcrumb'

const documentStore = useDocumentStore()
const uiStore = useUiStore()
const ebookStore = useEbookStore()
const mainContent = ref<HTMLElement | null>(null)

function toggleToc() {
  uiStore.toggleSidebar()
}

// Build ancestor chain for breadcrumb
const ancestorChain = computed(() => {
  if (!uiStore.activeSectionId) return []
  const chain = findAncestorChain(documentStore.sections, uiStore.activeSectionId)
  return chain.map((item, i) => ({
    id: item.id,
    title: item.title,
    type: item.type,
    number: documentStore.getNumbering(item.id),
    isRoot: i === 0,
    isLeaf: i === chain.length - 1
  }))
})

function findSectionById(sections: TocItem[], id: string): TocItem | null {
  for (const section of sections) {
    if (section.id === id) return section
    if (section.children) {
      const found = findSectionById(section.children, id)
      if (found) return found
    }
  }
  return null
}

let scrollTimeout: ReturnType<typeof setTimeout> | null = null

function handleScroll() {
  if (scrollTimeout) clearTimeout(scrollTimeout)
  scrollTimeout = setTimeout(() => {
    updateActiveSection()
  }, 50)
}

function updateActiveSection() {
  if (!mainContent.value) return

  const container = mainContent.value
  const containerRect = container.getBoundingClientRect()
  const scrollTop = container.scrollTop
  const sections = documentStore.sections

  let foundSection: TocItem | null = null

  function checkSection(section: TocItem) {
    const element = document.getElementById(section.id)
    if (!element) return

    const rect = element.getBoundingClientRect()
    // Convert viewport-relative position to scroll offset within the container
    const elementScrollTop = rect.top - containerRect.top + scrollTop

    if (elementScrollTop <= scrollTop + 200) {
      foundSection = section
    }
  }

  function walkSections(sects: TocItem[]) {
    for (const sect of sects) {
      checkSection(sect)
      if (sect.children) {
        walkSections(sect.children)
      }
    }
  }

  walkSections(sections)

  if (foundSection && foundSection.id !== uiStore.activeSectionId) {
    uiStore.setActiveSection(foundSection.id)
  }
}

// Navigate to an element by ID, scrolling within the main container
function navigateToId(id: string) {
  if (!mainContent.value) return

  const element = document.getElementById(id)
  if (!element) return

  const container = mainContent.value
  const containerRect = container.getBoundingClientRect()
  const elementRect = element.getBoundingClientRect()

  // Calculate scroll offset: element position relative to container + current scroll - offset for top bar
  const scrollTarget = elementRect.top - containerRect.top + container.scrollTop - 70
  container.scrollTo({ top: scrollTarget, behavior: 'smooth' })

  // Update URL hash without triggering another scroll
  history.replaceState(null, '', `#${id}`)
}

// Intercept all clicks on hash links (xref, TOC, etc.)
function handleDocumentClick(e: MouseEvent) {
  const target = e.target as HTMLElement
  const link = target.closest('a[href^="#"]') as HTMLAnchorElement | null
  if (!link) return

  e.preventDefault()
  const id = link.getAttribute('href')!.slice(1)
  if (id) {
    navigateToId(id)
  }
}

onMounted(() => {
  documentStore.loadFromWindow()

  // Clean up DOCBOOK_DATA from DOM to keep DOM small
  delete (window as any).DOCBOOK_DATA

  ebookStore.applyTheme()

  // Force close settings panel on mount
  if (ebookStore.settingsOpen.value) {
    ebookStore.toggleSettings()
  }

  // Open sidebar by default on desktop
  if (window.innerWidth >= 1024) {
    uiStore.openSidebar()
  }

  // Catch all hash-link clicks (xrefs, TOC items)
  document.addEventListener('click', handleDocumentClick)

  // Handle initial hash and browser back/forward
  window.addEventListener('hashchange', handleHashChange)

  // Global keyboard shortcuts
  document.addEventListener('keydown', handleGlobalKeydown)

  // Initial active section + handle hash from URL
  setTimeout(() => {
    updateActiveSection()
    handleHashChange()
  }, 200)
})

onUnmounted(() => {
  document.removeEventListener('click', handleDocumentClick)
  window.removeEventListener('hashchange', handleHashChange)
  document.removeEventListener('keydown', handleGlobalKeydown)
})

function handleHashChange() {
  const hash = window.location.hash
  if (!hash) return
  const id = hash.slice(1)
  if (id) {
    // Small delay to ensure Vue has rendered the content
    setTimeout(() => navigateToId(id), 100)
  }
}

function handleGlobalKeydown(e: KeyboardEvent) {
  if (e.key === '/' && !isInputFocused()) {
    e.preventDefault()
    uiStore.openSearch()
  }
  if (e.key === 'Escape') {
    if (uiStore.searchOpen) {
      uiStore.closeSearch()
    }
    if (uiStore.sidebarOpen) {
      uiStore.closeSidebar()
    }
  }
}

function isInputFocused(): boolean {
  const active = document.activeElement
  return active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement
}
</script>

<style scoped>
.app-footer {
  border-color: var(--ebook-border);
  color: var(--ebook-text-muted);
}

.app-footer-link {
  color: var(--ebook-link-color);
}
</style>
