<template>
  <EbookContainer :class="['h-screen overflow-hidden', ebookStore.getThemeClass()]" :style="ebookStore.getCssVariables()">
    <!-- Skip to content (accessibility) -->
    <a href="#main-content" class="skip-link" @click.prevent="skipToContent">Skip to content</a>

    <!-- Reading progress bar -->
    <ReadingProgressBar :progress="readingProgress" :visible="ebookStore.showProgress.value" />

    <!-- Mobile overlay -->
    <div
      v-if="uiStore.sidebarOpen"
      @click="handleOverlayClick"
      class="fixed inset-0 bg-black/50 z-40"
      :class="{ 'lg:hidden': !ebookStore.focusMode.value }"
    ></div>

    <AppSidebar v-show="!ebookStore.focusMode.value || uiStore.sidebarOpen" />

    <!-- Ebook Top Bar -->
    <div :class="['focus-mode-topbar', { 'focus-mode-topbar--hidden': ebookStore.focusMode.value && !uiStore.sidebarOpen && !focusRevealTopbar, 'focus-mode-topbar--reveal': (ebookStore.focusMode.value && focusRevealTopbar) || (ebookStore.focusMode.value && uiStore.sidebarOpen) }]">
      <EbookTopBar
        :title="documentStore.title"
        :sidebar-open="uiStore.sidebarOpen"
        @toggle-toc="toggleToc"
        @toggle-settings="ebookStore.toggleSettings"
      />
    </div>

    <!-- Focus mode indicator -->
    <button
      v-if="ebookStore.focusMode.value && !uiStore.sidebarOpen"
      @click="exitFocusMode"
      class="focus-mode-indicator"
      title="Exit focus mode (f)"
    >
      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.878 9.878L3 3m6.878 6.878L21 21"/></svg>
      Focus mode
    </button>

    <!-- TTS indicator -->
    <div v-if="tts.speaking.value" class="tts-indicator">
      <button @click="tts.speak()" class="tts-btn" :title="tts.paused.value ? 'Resume' : 'Pause'">
        <svg v-if="tts.paused.value" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"/></svg>
        <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 9v6m4-6v6m7-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </button>
      <span class="tts-label">{{ tts.paused.value ? 'Paused' : 'Speaking...' }}</span>
      <button @click="tts.stop()" class="tts-btn" title="Stop">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 10a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1v-4z"/></svg>
      </button>
    </div>

    <main ref="mainContent" id="main-content" role="main" :class="[
      'h-screen overflow-y-auto transition-all duration-200',
      !ebookStore.focusMode.value ? 'pt-14' : 'pt-0',
      uiStore.sidebarOpen ? 'lg:pl-[280px]' : '',
      ebookStore.readingMode.value === 'paged' ? 'paged-mode' : ''
    ]" @scroll="handleScroll">
      <!-- Active section breadcrumb -->
      <BreadcrumbBar v-if="ancestorChain.length > 0 && !ebookStore.focusMode.value" :ancestor-chain="ancestorChain" />

      <div class="px-6 py-10 lg:px-8 lg:py-12 mx-auto transition-[max-width] duration-300 ease-out" :style="contentStyle">
        <!-- Title page -->
        <TitlePage
          v-if="documentStore.title && documentStore.title !== 'DocBook Document'"
          :title="documentStore.title"
          :subtitle="documentStore.subtitle"
          :author="documentStore.author"
          :pubdate="documentStore.pubdate"
          :copyright="documentStore.copyright"
        />

        <!-- DocbookMirror format (ProseMirror-style) -->
        <div v-if="documentStore.mirrorDocument" class="db-content">
          <!-- Reference card swiper mode -->
          <RefCardSwiper
            v-if="ebookStore.refCardMode.value && refEntries.length > 0"
            :entries="refEntries"
          />
          <!-- Default mirror renderer -->
          <MirrorRenderer v-else :blocks="documentStore.mirrorDocument.content || []" />

          <!-- Lists of figures/tables/examples -->
          <ListOfSection
            v-if="hasLists"
            :list-of="documentStore.listOf"
          />
        </div>

        <!-- Footer -->
        <footer class="app-footer mt-16 pt-8 border-t text-center text-sm">
          Generated by <a href="https://github.com/metanorma/metanorma-docbook" class="app-footer-link hover:underline">Metanorma Docbook</a> gem
        </footer>
      </div>
    </main>

    <SearchModal />
    <SettingsPanel />
    <ImageLightbox
      :visible="lightbox.visible"
      :src="lightbox.src"
      :alt="lightbox.alt"
      :title="lightbox.title"
      @close="lightbox.visible = false"
    />

    <!-- Keyboard help overlay -->
    <KeyboardHelp :visible="showKeyboardHelp" @close="showKeyboardHelp = false" />

    <!-- Section prev/next navigation -->
    <SectionNav
      :section-ids="sectionIds"
      :active-index="activeSectionIndex"
      :visible="showSectionNav"
      @navigate="navigateToId"
    />

    <!-- Back to top -->
    <Transition name="back-to-top-fade">
      <button v-if="showBackToTop" class="back-to-top" @click="scrollToTop" title="Back to top">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7"/>
        </svg>
      </button>
    </Transition>

    <!-- Screen reader announcements -->
    <div role="status" aria-live="polite" aria-atomic="true" class="sr-only">{{ sectionAnnouncement }}</div>

    <!-- Page navigation for paged mode -->
    <div v-if="ebookStore.readingMode.value === 'paged'" class="page-nav">
      <button @click="prevPage" :disabled="currentPage <= 1" class="page-nav-btn" title="Previous page">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"/></svg>
      </button>
      <span class="page-nav-info">{{ currentPage }} / {{ totalPages }}</span>
      <button @click="nextPage" :disabled="currentPage >= totalPages" class="page-nav-btn" title="Next page">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
      </button>
    </div>

    <!-- Reading ruler -->
    <div
      v-if="rulerEnabled && rulerY >= 0"
      class="reading-ruler"
      :style="{ top: rulerY + 'px' }"
    ></div>
  </EbookContainer>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, computed, ref, reactive, provide, watch, nextTick } from 'vue'
import { useDocumentStore, type TocItem } from '@/stores/documentStore'
import { useUiStore } from '@/stores/uiStore'
import { useEbookStore } from '@/composables/useEbookStore'
import { useLazySections } from '@/composables/useLazySections'
import { usePaginatedMode } from '@/composables/usePaginatedMode'
import { useReadingRuler } from '@/composables/useReadingRuler'
import { useBookmarks } from '@/composables/useBookmarks'
import { useReadingStats } from '@/composables/useReadingStats'
import { useTts } from '@/composables/useTts'
import AppSidebar from '@/components/AppSidebar.vue'
import SearchModal from '@/components/SearchModal.vue'
import SettingsPanel from '@/components/SettingsPanel.vue'
import MirrorRenderer from '@/components/MirrorRenderer.vue'
import RefCardSwiper from '@/components/RefCardSwiper.vue'
import EbookTopBar from '@/components/EbookTopBar.vue'
import EbookContainer from '@/components/EbookContainer.vue'
import BreadcrumbBar from '@/components/BreadcrumbBar.vue'
import ImageLightbox from '@/components/ImageLightbox.vue'
import ListOfSection from '@/components/ListOfSection.vue'
import ReadingProgressBar from '@/components/ReadingProgressBar.vue'
import KeyboardHelp from '@/components/KeyboardHelp.vue'
import SectionNav from '@/components/SectionNav.vue'
import TitlePage from '@/components/TitlePage.vue'
import { findAncestorChain } from '@/utils/breadcrumb'

const documentStore = useDocumentStore()
const uiStore = useUiStore()
const ebookStore = useEbookStore()
const mainContent = ref<HTMLElement | null>(null)

// Lazy section rendering
const { isVisible, observeSection, initialized: lazyInitialized } = useLazySections(mainContent)
provide('lazySectionVisible', isVisible)
provide('lazyObserveSection', observeSection)
provide('lazyInitialized', lazyInitialized)

// Paginated reading mode
const {
  currentPage, totalPages, progress: pageProgress,
  calculatePages, nextPage, prevPage, handleScroll: handlePagedScroll,
} = usePaginatedMode(mainContent)

// Recalculate pages when reading mode or document changes
watch(() => [ebookStore.readingMode.value, documentStore.mirrorDocument], () => {
  nextTick(() => calculatePages())
}, { immediate: false })

// Reading ruler
const { enabled: rulerEnabled, rulerY, toggle: toggleRuler } = useReadingRuler()

// Bookmarks
const bookmarks = useBookmarks(documentStore.title)
provide('bookmarks', bookmarks)

// Compute content style directly from store state (bypasses CSS variable cascade issues)
const contentStyle = computed(() => {
  const vars = ebookStore.getCssVariables()
  return {
    maxWidth: vars['--ebook-max-width'],
    margin: '0 auto',
  }
})

// Reading progress
const readingProgress = ref(0)

// Keyboard help overlay
const showKeyboardHelp = ref(false)

// Focus mode: reveal topbar on mouse proximity to top
const focusRevealTopbar = ref(false)

// Back to top button
const showBackToTop = ref(false)

// Image lightbox state
const lightbox = reactive({ visible: false, src: '', alt: '', title: '' })

provide('lightbox', {
  open(src: string, alt?: string, title?: string) {
    lightbox.visible = true
    lightbox.src = src
    lightbox.alt = alt || ''
    lightbox.title = title || ''
  }
})

provide('navigateToId', navigateToId)

function toggleToc() {
  uiStore.toggleSidebar()
}

function exitFocusMode() {
  ebookStore.setFocusMode(false)
}

function handleOverlayClick() {
  uiStore.closeSidebar()
}

// Lists of figures/tables/examples
const hasLists = computed(() => {
  const lo = documentStore.listOf
  return (lo.figures?.length ?? 0) + (lo.tables?.length ?? 0) + (lo.examples?.length ?? 0) > 0
})

// Build ancestor chain for breadcrumb
const ancestorChain = computed(() => {
  if (!uiStore.activeSectionId) return []
  const chain = findAncestorChain(documentStore.sections, uiStore.activeSectionId)
  return chain.map((item, i) => ({
    id: item.id,
    title: item.title,
    type: item.type,
    number: documentStore.getNumbering(item.id),
    isRoot: i === 0,
    isLeaf: i === chain.length - 1
  }))
})

function findSectionById(sections: TocItem[], id: string): TocItem | null {
  for (const section of sections) {
    if (section.id === id) return section
    if (section.children) {
      const found = findSectionById(section.children, id)
      if (found) return found
    }
  }
  return null
}

let scrollTimeout: ReturnType<typeof setTimeout> | null = null

function handleScroll() {
  if (ebookStore.readingMode.value === 'paged') {
    handlePagedScroll()
  }
  if (scrollTimeout) clearTimeout(scrollTimeout)
  scrollTimeout = setTimeout(() => {
    updateActiveSection()
  }, 50)
  // Update reading progress
  const container = mainContent.value
  if (container) {
    const scrollable = container.scrollHeight - container.clientHeight
    readingProgress.value = scrollable > 0 ? Math.min(100, Math.max(0, (container.scrollTop / scrollable) * 100)) : 0
    showBackToTop.value = container.scrollTop > container.clientHeight * 3
  }
}

function updateActiveSection() {
  if (!mainContent.value) return

  const container = mainContent.value
  const containerRect = container.getBoundingClientRect()
  const scrollTop = container.scrollTop
  const sections = documentStore.sections

  let foundSection: TocItem | null = null

  function checkSection(section: TocItem) {
    const element = document.getElementById(section.id)
    if (!element) return

    const rect = element.getBoundingClientRect()
    // Convert viewport-relative position to scroll offset within the container
    const elementScrollTop = rect.top - containerRect.top + scrollTop

    if (elementScrollTop <= scrollTop + 200) {
      foundSection = section
    }
  }

  function walkSections(sects: TocItem[]) {
    for (const sect of sects) {
      checkSection(sect)
      if (sect.children) {
        walkSections(sect.children)
      }
    }
  }

  walkSections(sections)

  if (foundSection && foundSection.id !== uiStore.activeSectionId) {
    uiStore.setActiveSection(foundSection.id)
    readingStats.markSectionRead(foundSection.id)
    readingStats.recordActivity()
    history.replaceState(null, '', `#${foundSection.id}`)
    try {
      localStorage.setItem('docbook-position-' + documentStore.title, foundSection.id)
    } catch {}
  }
}

// Flatten section IDs in document order for keyboard navigation
const sectionIds = computed(() => {
  const ids: string[] = []
  function walk(items: TocItem[]) {
    for (const item of items) {
      ids.push(item.id)
      if (item.children) walk(item.children)
    }
  }
  walk(documentStore.sections)
  return ids
})

// Active section index for SectionNav
const activeSectionIndex = computed(() =>
  sectionIds.value.indexOf(uiStore.activeSectionId || '')
)

// Reading statistics
const readingStats = useReadingStats(
  documentStore.title,
  sectionIds.value.length,
  sectionIds.value
)
provide('readingStats', readingStats)

// Text-to-speech
const tts = useTts()

// Refentry card swiper: extract refentries from document
const refEntries = computed(() => {
  const doc = documentStore.mirrorDocument
  if (!doc?.content) return []
  const entries: any[] = []
  function collect(nodes: any[]) {
    for (const node of nodes) {
      if (node.type === 'refentry') {
        entries.push(node)
      }
      if (node.content) collect(node.content)
    }
  }
  collect(doc.content)
  return entries
})

// Show section nav when scrolled past first section and not in focus mode
const showSectionNav = computed(() =>
  !ebookStore.focusMode.value && activeSectionIndex.value >= 0
)

// Screen reader announcement for section changes
const sectionAnnouncement = computed(() => {
  const id = uiStore.activeSectionId
  if (!id) return ''
  const section = findSectionById(documentStore.sections, id)
  return section ? section.title : ''
})

// Navigate to an element by ID, scrolling within the main container
function navigateToId(id: string) {
  if (!mainContent.value) return

  const element = document.getElementById(id)
  if (!element) return

  const container = mainContent.value
  const containerRect = container.getBoundingClientRect()
  const elementRect = element.getBoundingClientRect()

  // Calculate scroll offset: element position relative to container + current scroll - offset for top bar
  const scrollTarget = elementRect.top - containerRect.top + container.scrollTop - 70
  container.scrollTo({ top: scrollTarget, behavior: 'smooth' })

  // Update URL hash without triggering another scroll
  history.replaceState(null, '', `#${id}`)
}

// Intercept all clicks on hash links (xref, TOC, etc.)
function handleDocumentClick(e: MouseEvent) {
  const target = e.target as HTMLElement
  const link = target.closest('a[href^="#"]') as HTMLAnchorElement | null
  if (!link) return

  e.preventDefault()
  const id = link.getAttribute('href')!.slice(1)
  if (id) {
    navigateToId(id)
  }
}

onMounted(() => {
  documentStore.loadFromWindow()

  // Clean up DOCBOOK_DATA from DOM to keep DOM small
  delete (window as any).DOCBOOK_DATA

  ebookStore.applyTheme()

  // Force close settings panel on mount
  if (ebookStore.settingsOpen.value) {
    ebookStore.toggleSettings()
  }

  // Open sidebar by default on desktop
  if (window.innerWidth >= 1024) {
    uiStore.openSidebar()
  }

  // Catch all hash-link clicks (xrefs, TOC items)
  document.addEventListener('click', handleDocumentClick)

  // Handle initial hash and browser back/forward
  window.addEventListener('hashchange', handleHashChange)

  // Global keyboard shortcuts
  document.addEventListener('keydown', handleGlobalKeydown)

  // Focus mode: reveal topbar on mouse near top
  document.addEventListener('mousemove', handleMouseMove)

  // Initial active section + handle hash from URL
  setTimeout(() => {
    updateActiveSection()
    handleHashChange()
    // Calculate pages for paged mode after content renders
    calculatePages()
    // Restore saved reading position if no URL hash was provided
    if (!window.location.hash) {
      try {
        const saved = localStorage.getItem('docbook-position-' + documentStore.title)
        if (saved) {
          const el = document.getElementById(saved)
          if (el) navigateToId(saved)
        }
      } catch {}
    }
  }, 200)
})

onUnmounted(() => {
  document.removeEventListener('click', handleDocumentClick)
  window.removeEventListener('hashchange', handleHashChange)
  document.removeEventListener('keydown', handleGlobalKeydown)
  document.removeEventListener('mousemove', handleMouseMove)
})

function handleHashChange() {
  const hash = window.location.hash
  if (!hash) return
  const id = hash.slice(1)
  if (id) {
    // Small delay to ensure Vue has rendered the content
    setTimeout(() => navigateToId(id), 100)
  }
}

function handleGlobalKeydown(e: KeyboardEvent) {
  const inputFocused = isInputFocused()

  if (e.key === '/' && !inputFocused) {
    e.preventDefault()
    uiStore.openSearch()
  }

  if (e.key === 'Escape') {
    if (showKeyboardHelp.value) {
      showKeyboardHelp.value = false
      return
    }
    if (ebookStore.settingsOpen.value) {
      ebookStore.toggleSettings()
      return
    }
    if (uiStore.searchOpen) {
      uiStore.closeSearch()
      return
    }
    if (uiStore.sidebarOpen) {
      uiStore.closeSidebar()
      return
    }
  }

  if (inputFocused) return

  // Toggle keyboard help
  if (e.key === '?') {
    e.preventDefault()
    showKeyboardHelp.value = !showKeyboardHelp.value
    return
  }

  // Toggle settings
  if (e.key === 's') {
    e.preventDefault()
    ebookStore.toggleSettings()
    return
  }

  // Toggle focus mode
  if (e.key === 'f') {
    e.preventDefault()
    ebookStore.toggleFocusMode()
    return
  }

  // Toggle reading ruler
  if (e.key === 'r') {
    e.preventDefault()
    toggleRuler()
    return
  }

  // Toggle bookmark for active section
  if (e.key === 'b') {
    e.preventDefault()
    const activeId = uiStore.activeSectionId
    if (activeId) {
      const section = findSectionById(documentStore.sections, activeId)
      if (section) {
        bookmarks.toggle(activeId, section.title)
      }
    }
    return
  }

  // TTS play/pause (Shift+P)
  if (e.key === 'P') {
    e.preventDefault()
    if (tts.speaking.value) {
      tts.speak() // toggles pause/resume
    } else {
      tts.speak()
    }
    return
  }

  // TTS stop
  if (e.key === 'p' && tts.speaking.value) {
    e.preventDefault()
    tts.stop()
    return
  }

  // Toggle sidebar
  if (e.key === 't') {
    e.preventDefault()
    uiStore.toggleSidebar()
    return
  }

  // j/k navigation between sections
  if (sectionIds.value.length > 0) {
    const current = sectionIds.value.indexOf(uiStore.activeSectionId || '')
    if (e.key === 'j' && current < sectionIds.value.length - 1) {
      e.preventDefault()
      navigateToId(sectionIds.value[current + 1])
    }
    if (e.key === 'k' && current > 0) {
      e.preventDefault()
      navigateToId(sectionIds.value[current - 1])
    }
  }

  // Page navigation in paged mode
  if (ebookStore.readingMode.value === 'paged') {
    if (e.key === 'ArrowRight' || e.key === ' ') {
      e.preventDefault()
      nextPage()
      return
    }
    if (e.key === 'ArrowLeft') {
      e.preventDefault()
      prevPage()
      return
    }
  }
}

function handleMouseMove(e: MouseEvent) {
  focusRevealTopbar.value = ebookStore.focusMode.value && e.clientY < 48
}

function scrollToTop() {
  mainContent.value?.scrollTo({ top: 0, behavior: 'smooth' })
}

function skipToContent() {
  mainContent.value?.focus()
  mainContent.value?.scrollTo({ top: 0 })
}

function isInputFocused(): boolean {
  const active = document.activeElement
  return active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement
}
</script>

<style scoped>
.skip-link {
  position: absolute;
  top: -100px;
  left: 0;
  background: var(--chrome-accent);
  color: #fff;
  padding: 8px 16px;
  z-index: 100;
  font-size: 0.85rem;
  font-weight: 600;
  border-radius: 0 0 8px 0;
  text-decoration: none;
  transition: top 0.1s;
}

.skip-link:focus {
  top: 0;
}

.app-footer {
  border-color: var(--ebook-border);
  color: var(--ebook-text-muted);
}

.app-footer-link {
  color: var(--ebook-link-color);
}

.focus-mode-topbar {
  transition: opacity 0.2s ease;
}

.focus-mode-topbar--hidden {
  opacity: 0;
  pointer-events: none;
}

.focus-mode-topbar--reveal {
  opacity: 1;
  pointer-events: auto;
}

.focus-mode-indicator {
  position: fixed;
  bottom: 24px;
  right: 24px;
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 14px;
  font-size: 0.75rem;
  font-weight: 500;
  border-radius: 999px;
  background: var(--chrome-accent);
  color: #fff;
  border: none;
  cursor: pointer;
  box-shadow: 0 2px 12px rgba(0,0,0,0.2);
  transition: opacity 0.2s ease, transform 0.2s ease;
  z-index: 30;
}
.focus-mode-indicator:hover {
  opacity: 0.9;
  transform: scale(1.05);
}

.back-to-top {
  position: fixed;
  bottom: 24px;
  right: 24px;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--chrome-bg-glass);
  color: var(--chrome-text);
  border: 1px solid var(--chrome-border);
  backdrop-filter: blur(8px);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.12);
  cursor: pointer;
  z-index: 35;
  transition: background 0.15s ease, transform 0.15s ease;
}

.back-to-top:hover {
  background: var(--chrome-bg-hover);
  transform: translateY(-2px);
}

.back-to-top-fade-enter-active,
.back-to-top-fade-leave-active {
  transition: opacity 0.2s ease, transform 0.2s ease;
}
.back-to-top-fade-enter-from,
.back-to-top-fade-leave-to {
  opacity: 0;
  transform: translateY(16px);
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

/* Paged reading mode */
.paged-mode {
  scroll-snap-type: y mandatory;
  scroll-behavior: smooth;
}

/* Page navigation */
.page-nav {
  position: fixed;
  bottom: 24px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 8px 16px;
  background: var(--chrome-bg-glass);
  border: 1px solid var(--chrome-border);
  border-radius: 999px;
  backdrop-filter: blur(8px);
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.12);
  z-index: 40;
}

.page-nav-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  color: var(--chrome-text);
  transition: background 0.15s ease;
}

.page-nav-btn:hover:not(:disabled) {
  background: var(--chrome-bg-hover);
}

.page-nav-btn:disabled {
  opacity: 0.3;
  cursor: default;
}

.page-nav-info {
  font-size: 0.8rem;
  font-weight: 500;
  color: var(--chrome-text-dim);
  min-width: 60px;
  text-align: center;
  font-variant-numeric: tabular-nums;
}

/* Reading ruler */
.reading-ruler {
  position: fixed;
  left: 0;
  right: 0;
  height: 2em;
  pointer-events: none;
  z-index: 25;
  background: color-mix(in srgb, var(--ebook-accent) 12%, transparent);
  border-top: 1px solid color-mix(in srgb, var(--ebook-accent) 30%, transparent);
  border-bottom: 1px solid color-mix(in srgb, var(--ebook-accent) 30%, transparent);
  transform: translateY(-1em);
  transition: top 0.05s ease-out;
}

/* TTS indicator */
.tts-indicator {
  position: fixed;
  bottom: 24px;
  left: 24px;
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 14px;
  font-size: 0.75rem;
  font-weight: 500;
  border-radius: 999px;
  background: var(--chrome-accent);
  color: #fff;
  border: none;
  box-shadow: 0 2px 12px rgba(0,0,0,0.2);
  z-index: 30;
}

.tts-btn {
  display: flex;
  align-items: center;
  color: #fff;
  opacity: 0.8;
  transition: opacity 0.15s ease;
}

.tts-btn:hover {
  opacity: 1;
}

.tts-label {
  font-size: 0.75rem;
}
</style>
