<template>
  <EbookContainer :class="['h-screen overflow-hidden', ebookStore.getThemeClass()]" :style="ebookStore.getCssVariables()">
    <!-- Mobile overlay -->
    <div
      v-if="uiStore.sidebarOpen"
      @click="uiStore.closeSidebar"
      class="fixed inset-0 bg-black/50 z-40 lg:hidden"
    ></div>

    <AppSidebar />

    <!-- Ebook Top Bar -->
    <EbookTopBar
      :title="documentStore.title"
      :sidebar-open="uiStore.sidebarOpen"
      @toggle-toc="toggleToc"
      @toggle-settings="ebookStore.toggleSettings"
    />

    <main ref="mainContent" :class="[
      'h-screen overflow-y-auto pt-14 transition-all duration-200',
      uiStore.sidebarOpen ? 'lg:pl-[280px]' : ''
    ]" @scroll="handleScroll">
      <!-- Active section breadcrumb -->
      <div v-if="activeSection" class="sticky top-0 z-10 border-b backdrop-blur-sm px-6 py-2 text-sm"
           :class="[
             'bg-white/90 dark:bg-gray-900/90 border-gray-200 dark:border-gray-700',
             'text-gray-600 dark:text-gray-400'
           ]">
        <div class="max-w-4xl mx-auto flex items-center gap-2">
          <span v-if="activeSectionParent" :class="['text-gray-900', 'dark:text-gray-100']">{{ activeSectionParent.title }} /</span>
          <span class="font-medium" :class="['text-gray-900 dark:text-gray-100']">{{ activeSection.title }}</span>
        </div>
      </div>

      <div class="px-6 py-10 lg:px-8 lg:py-12 mx-auto" :style="{ maxWidth: '72rem', margin: '0 auto' }">
        <!-- Article content (no sections) -->
        <div v-if="!hasSections" class="db-content">
          <BlockRenderer v-if="articleContent" :blocks="articleContent.blocks" />
        </div>

        <!-- Section content -->
        <template v-else>
          <div v-for="section in documentStore.sections" :key="section.id">
            <ChapterSection v-if="section.type === 'chapter'" :section="section" />
            <AppendixSection v-else-if="section.type === 'appendix'" :section="section" />
            <PartSection v-else-if="section.type === 'part'" :section="section" />
            <SectionContent v-else :section="section" />
          </div>
        </template>

        <!-- Footer -->
        <footer class="mt-16 pt-8 border-t text-center text-sm" :class="['border-gray-200 dark:border-gray-700', 'text-gray-500 dark:text-gray-400']">
          Generated by <a href="https://github.com/metanorma/metanorma-docbook" class="hover:underline" :class="['text-blue-600 dark:text-blue-400']">Metanorma Docbook</a> gem
        </footer>
      </div>
    </main>

    <SearchModal />
    <SettingsPanel />

    <!-- Keyboard shortcut listener -->
    <Teleport to="body">
      <div @keydown="handleGlobalKeydown"></div>
    </Teleport>
  </EbookContainer>
</template>

<script setup lang="ts">
import { onMounted, computed, ref } from 'vue'
import { useDocumentStore, type TocItem } from '@/stores/documentStore'
import { useUiStore } from '@/stores/uiStore'
import { useEbookStore } from '@/composables/useEbookStore'
import AppSidebar from '@/components/AppSidebar.vue'
import SearchModal from '@/components/SearchModal.vue'
import SettingsPanel from '@/components/SettingsPanel.vue'
import ChapterSection from '@/components/ChapterSection.vue'
import AppendixSection from '@/components/AppendixSection.vue'
import PartSection from '@/components/PartSection.vue'
import SectionContent from '@/components/SectionContent.vue'
import BlockRenderer from '@/components/BlockRenderer.vue'
import EbookTopBar from '@/components/EbookTopBar.vue'
import EbookContainer from '@/components/EbookContainer.vue'

const documentStore = useDocumentStore()
const uiStore = useUiStore()
const ebookStore = useEbookStore()
const mainContent = ref<HTMLElement | null>(null)

function toggleToc() {
  uiStore.toggleSidebar()
}

const hasSections = computed(() => documentStore.sections && documentStore.sections.length > 0)

// Article content for documents without sections
const articleContent = computed(() => documentStore.getSectionContent('article-content'))

// Find the currently active section based on scroll position
const activeSection = computed(() => {
  if (!uiStore.activeSectionId) return null
  return findSectionById(documentStore.sections, uiStore.activeSectionId)
})

// Find parent section if active section is nested
const activeSectionParent = computed((): TocItem | null => {
  if (!uiStore.activeSectionId) return null
  for (const section of documentStore.sections) {
    if (section.children && section.children.some(c => c.id === uiStore.activeSectionId)) {
      return section
    }
  }
  return null
})

function findSectionById(sections: TocItem[], id: string): TocItem | null {
  for (const section of sections) {
    if (section.id === id) return section
    if (section.children) {
      const found = findSectionById(section.children, id)
      if (found) return found
    }
  }
  return null
}

let scrollTimeout: ReturnType<typeof setTimeout> | null = null

function handleScroll() {
  if (scrollTimeout) clearTimeout(scrollTimeout)
  scrollTimeout = setTimeout(() => {
    updateActiveSection()
  }, 50)
}

function updateActiveSection() {
  if (!mainContent.value) return

  const scrollTop = mainContent.value.scrollTop
  const sections = documentStore.sections

  let foundSection: TocItem | null = null

  function checkSection(section: TocItem) {
    const element = document.getElementById(section.id)
    if (!element) return

    const rect = element.getBoundingClientRect()
    const offsetTop = rect.top + scrollTop - 100

    if (scrollTop >= offsetTop - 100) {
      foundSection = section
    }
  }

  function walkSections(sects: TocItem[]) {
    for (const sect of sects) {
      checkSection(sect)
      if (sect.children) {
        walkSections(sect.children)
      }
    }
  }

  walkSections(sections)

  if (foundSection && (foundSection as TocItem).id !== uiStore.activeSectionId) {
    uiStore.setActiveSection((foundSection as TocItem).id)
  }
}

onMounted(() => {
  documentStore.loadFromWindow()

  // Clean up DOCBOOK_DATA from DOM to keep DOM small
  delete (window as any).DOCBOOK_DATA

  ebookStore.applyTheme()

  // Force close settings panel on mount
  if (ebookStore.settingsOpen.value) {
    ebookStore.toggleSettings()
  }

  // Open sidebar by default on desktop
  if (window.innerWidth >= 1024) {
    uiStore.openSidebar()
  }

  // Handle hash navigation for anchor links
  handleHashNavigation()
  window.addEventListener('hashchange', handleHashNavigation)

  // Global keyboard shortcuts
  document.addEventListener('keydown', handleGlobalKeydown)

  // Initial active section
  setTimeout(updateActiveSection, 100)
})

function handleHashNavigation() {
  const hash = window.location.hash
  if (!hash) return
  const id = hash.slice(1) // remove #
  const element = document.getElementById(id)
  if (element) {
    element.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }
}

function handleGlobalKeydown(e: KeyboardEvent) {
  if (e.key === '/' && !isInputFocused()) {
    e.preventDefault()
    uiStore.openSearch()
  }
  if (e.key === 'Escape') {
    if (uiStore.searchOpen) {
      uiStore.closeSearch()
    }
    if (uiStore.sidebarOpen) {
      uiStore.closeSidebar()
    }
  }
}

function isInputFocused(): boolean {
  const active = document.activeElement
  return active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement
}
</script>
